# certificate settings
certificate:
  generate: true

webhook:
  # webhook failure policy (Ignore / Fail)
  failurePolicy: "Ignore"
  timeoutSeconds: 10

dockerImage: "ghcr.io/troop-dev/k8s-pod-labeler"
containerPort: 8443

# image pull secrets for the pod labeler
# imagePullSecrets:
# - name: some-secret
imagePullSecrets: []

# specify the labels/annotations to apply
# appInputs:
#   labels:
#     "foo": "bar"
#   annotations:
#     "bar": "baz"
appInputs:
  labels: {}
  annotations: {}

containerResources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

objectSelector: {}

namespaceSelector:
  matchExpressions:
  - key: troop.com/k8s-pod-labeler
    operator: In
    values:
    - enabled
  - key: troop.com/k8s-pod-labeler
    operator: NotIn
    values:
    - disabled
