apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pod-labeler
  labels:
    app: k8s-pod-labeler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-pod-labeler
  template:
    metadata:
      name: k8s-pod-labeler
      labels:
        app: k8s-pod-labeler
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: mutator
        image: "{{ .Values.dockerImage }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: Always
        resources:
        {{- toYaml .Values.containerResources | nindent 10 }}
        env:
          - name: PORT
            value: "{{ .Values.containerPort }}"
          - name: K8S_LABELS
            value: {{ .Values.appInputs.labels | toJson | b64enc }}
          - name: K8S_ANNOTATIONS
            value: {{ .Values.appInputs.annotations | toJson | b64enc }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - name: certs
          mountPath: /etc/webhook/certs
          readOnly: true
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: {{ .Values.containerPort }}
      volumes:
        - name: certs
          secret:
            secretName: k8s-pod-labeler
